name: Remover SNS Actions de Alarmes

on:
  workflow_dispatch:
    inputs:
      sns_topic:
        description: 'ARN do tópico SNS a remover das actions'
        required: true

jobs:
  remove-sns-actions:
    runs-on: ubuntu-latest
    environment: aws-remover-sns
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Rodar script Python para remover ações
        run: |
          python main.py "${{ github.event.inputs.sns_topic }}"
