name: Remover SNS Actions de Alarmes

on:
  workflow_dispatch:
    inputs:
      sns_topic:
        description: 'ARN do tópico SNS a remover das actions'
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_PARAMETER: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  remove-sns-actions:
    runs-on: ubuntu-latest
    environment: aws-remover-sns

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Verificar AWS CLI
        run: aws --version

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE_PARAMETER }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Rodar script Python para remover ações
        run: |
          python remover_actions.py "${{ github.event.inputs.sns_topic }}"
