name: Remover SNS Actions de Alarmes

on:
  workflow_dispatch:
    inputs:
      sns_topic:
        description: 'ARN do tópico SNS a remover das actions'
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_PARAMETER: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  remove-sns-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Obter ARN da Role via Parameter Store
        id: ssm
        run: |
          ROLE=$(aws ssm get-parameter \
            --name "$ROLE_PARAMETER" \
            --region $AWS_REGION \
            --query 'Parameter.Value' \
            --output text)
          echo "ROLE=$ROLE" >> $GITHUB_ENV

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE }}
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Rodar script Python para remover ações
        run: |
          python remover_actions.py "${{ github.event.inputs.sns_topic }}"
